### ISSUE TITLE
TS-Error when trying to create new instance of SteamMarket

### ISSUE THREAD

**Issue by Laurenz-M** [vladislav-puzyrev/steam-market#1]
Hey everyone, i was planning on using the steam-market api to fetch some data, but for some reason the example code in the 'Usage' section doesnt work for me. I am getting an 
" TS2351: This expression is not constructable.   Type 'typeof import("C:/Users/Name/IdeaProjects/ProjectName/node_modules/steam-market/build/index")' has no construct signatures. " typescript-error. I believe that i installed everything correcty but cant seem to get it to work.

This is my code:
`import SteamMarket from 'steam-market';
 const market = new SteamMarket();`
 
My tsconfig.json looks like this:

{
  "compilerOptions": {
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "target": "ES2020",
    "sourceMap": true,
    "outDir": "dist",
    "resolveJsonModule": true,
    "esModuleInterop": true
  },
  "ts-node": {
    "esm": true
  },
  "include": ["src/**/*"]
}

I would really appreciate some help, thanks so much in advance! :)

**Comment by vladpuz** [comment]
@Laurenz-M Hello.

I tested your code with your tsconfig in a minimal node.js application, but failed to reproduce the problem. Here is the application I tested on [testmarket.zip](https://github.com/vladislav-puzyrev/steam-market/files/10179737/testmarket.zip)

First install packages:
```bash
npm install
```

Works with `ts-node`:
```bash
ts-node src/main.ts
// or
npx ts-node src/main.ts
```

Also with  `tsc`:
```bash
tsc
node dist/main.js
// or
npx tsc
node dist/main.js
```

Let me know if I missed something.

**Comment by vladpuz** [comment]
The problem is in the ESM. If you add `"type": "module"` to the `package.json` of my example, the same error occurs.

I think it's worth implementing an ESM module system in the `steam-market`. As a temporary solution, you can disable `"type": "module"` in your `package.json` if possible.

**Comment by vladpuz** [comment]
Release 2.0.0 with ESM is available https://www.npmjs.com/package/steam-market
