### ISSUE TITLE
Request priceHistory fails

### ISSUE THREAD

**Issue by Laurenz-M** [vladislav-puzyrev/steam-market#2]
I have issues using the "priceHistory" method on the steam market. Using the code listed in the test-project [testmarket.zip](https://github.com/vladislav-puzyrev/steam-market/files/10259564/testmarket.zip)
(the same as provided by the author in issue #1 ), all i get back is an Error 'Bad request', despite providing the neccesary parameters. What makes this even weirder is, that "priceOverview" works perfectly with the same parameters, if used instead of "priceHistory" in line 11 of main.ts. I have tried multiple things to resolve the error and read the documentation carefully, but couldnt get it working. Did i miss something here? I thought about the official steam-api having changed its URL-Route for requesting the priceHistory. Maybe thats worth investigating, if the mistake is not mine.

Would be nice for you to look into.
Thanks and kind regards :)

**Comment by vladpuz** [comment]
@Laurenz-M Hello.

I was able to reproduce your problem, I'm getting a 400 http error. Apparently the `priceHistory` method does not work without specifying a cookie when I logged in with `steam-user` and previously called `market.setCookies` the request was successful.

You can take a look at an example:
[issue2.zip](https://github.com/vladislav-puzyrev/steam-market/files/10261524/issue2.zip)

First install packages:
```bash
npm install
```

Start with `ts-node`:
```bash
npm start
```

**Comment by Laurenz-M** [comment]
Hey @vladislav-puzyrev !
Thanks for your response!
I have just come across that possible solution. Is there a way to do this with an anonymous steam account rather to logging in with password and username?

Best wishes :)

**Comment by vladpuz** [comment]
I don't think it's possible. In the browser, `priceHistory` is called on the inventory page only if the login is complete. Otherwise prices are not shown.

**Comment by Laurenz-M** [comment]
> I don't think it's possible. In the browser, `priceHistory` is called on the inventory page only if the login is complete. Otherwise prices are not shown.

Alright, I already thought that might happen. Thanks so much anyways, great help! 
I dont know if this would make sense, but maybe it is worth adding a little sidenote of some sort to the docs that states this limitation.
Have a nice day! :)

**Comment by vladpuz** [comment]
Opened issue #3
