### ISSUE TITLE
myhistory endpoint for sale insides

### ISSUE THREAD

**Issue by K0IN** [vladislav-puzyrev/steam-market#4]
Can we get the endpoint (myhistory)[https://steamcommunity.com/market/myhistory/render/?query=&start=1&count=500]?
This would be very useful to see how much you sold per day or analyse sell frequency.

If you do not accept feature requests, can I create a PR for this?

**Comment by vladpuz** [comment]
@K0IN Hello. Thanks for your suggestion, it's really helpful to use.

It doesn't seem complicated, so I'll probably add a new method in the next few days.

**Comment by vladpuz** [comment]
New version `3.0.0-beta.1` is available on npm.

Install:
```bash
yarn add steam-market@beta
```

The new method `myHistory` required editing in existing types, so a major release is needed. Before the full 3.0.0 version, I also want to check the correctness of the typing of other methods.

**Comment by K0IN** [comment]
Works for me, thanks so much for the quick response!
